// Generated by CoffeeScript 2.0.0-beta4
var App, CFX, app;

import React from 'react';

import dva, {
  connect
} from 'dva';

import {
  Router,
  Route
} from 'dva/router';

import {
  prefixDom
} from 'cfx.dom';

// 1. Initializ
app = dva();

// 2. Model
app.model({
  namespace: 'count',
  state: 0,
  reducers: {
    add: function(count) {
      return count + 1;
    },
    minus: function(count) {
      return count - 1;
    }
  }
});

CFX = prefixDom({
  default: {'div': 'div', 'h2': 'h2', 'button': 'button'}
});

// 3. View
app.reducers = ({count}) => {
  return {count};
};

app.components = function(props) {
  var c_button, c_div, c_h2;
  ({c_div, c_h2, c_button} = CFX);
  return c_div({}, c_h2({}, props.count), c_button({
    key: "add",
    onClick: function() {
      return props.dispatch({
        type: 'count/add'
      });
    }
  }, "+"), c_button({
    key: "minus",
    onClick: function() {
      return props.dispatch({
        type: 'count/minus'
      });
    }
  }, "-"));
};

App = (connect(app.reducers))(app.components);

// 4. Router
app.router(({history}) => {
  // {
  //   c_Router
  //   c_Route
  // } = CFX
  return React.createElement(Router, {history}, React.createElement(Route, {
    path: "/",
    component: App
  }));
});

// 5. Start
app.start('#root');
